parameters:
  ns_flash.message.class: NS\FlashBundle\Service\Messages
  ns_flash.template: NSFlashBundle:Messages:index.html.twig
services:
  ns_flash:
    class: %ns_flash.message.class%
    arguments: [ @session, %ns_flash.template% ]
    tags:
      - { name: twig.extension }