parameters:
  ns_flash.template: NSFlashBundle:Messages:index.html.twig

services:
  NS\FlashBundle\Service\Messages:
    public: false
    arguments: [ "@session", "%ns_flash.template%" ]
    tags:
      - { name: twig.extension }

  NS\FlashBundle\Interfaces\MessageStore:
    alias: NS\FlashBundle\Service\Messages

  ns_flash:
    alias: NS\FlashBundle\Service\Messages
    public: true
