parameters:
  ns_flash.template: NSFlashBundle:Messages:index.html.twig

services:
  ns_flash:
    class: NS\FlashBundle\Service\Messages
    arguments: [ "@twig", "@session", %ns_flash.template% ]
    tags:
      - { name: twig.extension }
