parameters:
  ns_flash.template: NSFlashBundle:Messages:index.html.twig

services:
  NS\FlashBundle\Service\Messages:
    alias: ns_flash
    arguments: [ "@session", "%ns_flash.template%" ]
    tags:
      - { name: twig.extension }
